{
 "title": "少數派寫手數據",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "filter_title",
    "label": "標題",
    "query": {
     "query": "label_values(article_info{job=\"sspai-info\"},title)"
    }
   },
   {
    "name": "filter_type",
    "label": "類型",
    "query": {
     "query": "label_values(article_info{job=\"sspai-info\"},type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "少數派文章概覧",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "article_info{job=\"sspai-info\", title=~\"$filter_title\", type=~\"$filter_type\"}",
     "legendFormat": "{{title}} - {{type}}數"
    }
   ]
  },
  {
   "title": "點贊閱讀比",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "article_info{job=\"sspai-info\", type!=\"comments\", title=~\"$filter_title\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "文章之最",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "article_info{job=\"sspai-info\", type=~\"$filter_type\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}